favicon_image: 
seo: 
  site_name: Liederlauschen am Rand
  title: Für alle Musik- und Natur-Liebhaber, Familien und Fahrradfreunde!
  description: 
  keywords: 
  social_image: /images_impressionen/imp_01.jpg
  author: 
  favicon_image: 
social: 
  instagram_username: 
  facebook_url: 